### ISSUE TITLE
JDBC error when a query includes '{t'

### ISSUE THREAD

**Issue by kskim80** [bitnine-oss/agensgraph-jdbc#22]
If the following query is executed using JDBC prepared statement, it occurs:
org.postgresql.util.PSQLException: ERROR syntax error at or near "TIME" is occurred:

```sql
   CREATE (a:test {txid: ?})
```

It seems like that JDBC driver changes '{t' to 'TIME' automatically.
When investigating the prepared statement instance using IntelliJ debugger, the statement is printed like this:

```sql
  CREATE (a:test TIME xid: ? )
```

**Comment by mlogue** [comment]
This is caused by the JDBC escape syntax.
https://jdbc.postgresql.org/documentation/81/escapes.html

You can bypass it by inserting a space after `{`.
`CREATE (a:test { txid: ?})`

**Comment by kskim80** [comment]
This is a very serious problem.
We should modify the routine for detecting the escape syntax.
