### ISSUE TITLE
How to correctly use the merge clause in the perpared statment？

### ISSUE THREAD

**Issue by zzl221000** [bitnine-oss/agensgraph-jdbc#49]
When I use the merge clause in the perpared statment(multi-threaded environment), the merge sometimes has problems and still creates the existing nodes.
This is my pstmt：
> "merge (n:rlnode {rlid: '"+rlid1+"', name: '"+name1+"',label: '"+label1+"'})" +
> "merge (m:rlnode {rlid: '"+rlid2+"', name: '"+name2+"',label: '"+label2+"'})"+
> " merge (n)-[:knows " +know+ " ]->(m);"

Is pstmt batch execution merge not allowed?

**Comment by zzl221000** [comment]
use unique index get
> org.postgresql.util.PSQLException: ERROR: duplicate key value violates unique constraint "urlid"
Does this mean that merge does not work correctly?

**Comment by bylee5** [comment]
It work correctly.
If the above error occurs, must rollback for that session.
