### ISSUE TITLE
java driver spring boot cannot specify database in jdbc url

### ISSUE THREAD

**Issue by watery** [bitnine-oss/agensgraph-jdbc#61]
Hi, I've followed the Java driver connection [example in the docs](https://bitnine.net/documentations/manual/agens_graph_developer_manual_en.html#usage-of-the-java-driver) by almost literally copy-pasting it; the only difference being that I'm using Spring Boot, so the database connection is set up by specifying Spring datasource properties:

```
spring.datasource.driver-class-name=net.bitnine.agensgraph.Driver
spring.datasource.url=jdbc:agensgraph://<host>:<port>/agens
spring.datasource.username=postgres
spring.datasource.password=<passw>
```

But I get:

    FATAL: database "agens" does not exist

If I get rid of the `agens` subpath, turning the url into `jdbc:agensgraph://<host>:<port>/` the connection is fine. Though of course I need to issue a:

    databaseService.getJdbcTemplate().execute("SET graph_path=agens");

after datasource initialization to make the following queries work.

And this is what I get from the command line client:

```
agens -h <host> -p <port> -U postgres

postgres=# \dn
  List of schemas
  Name  |  Owner
--------+----------
 agens  | postgres
 public | postgres
(2 rows)

postgres=# \dG
  List of graphs
 Name  |  Owner
-------+----------
 agens | postgres
(1 row)
```

hence I guess that the full JDBC url `jdbc:agensgraph://<host>:<port>/agens` should work.

Am I missing something?

As I side note, AgensGraph is currently deployed in a Docker container using [turicas Docker image](https://github.com/turicas/agensgraph-docker).

**Comment by emotionbug** [comment]
I think you want to connect with `SET GRAPH_PATH` command right?
but, Basically, `Graph` implemented `Schema`. not, `Database`.

it means, JDBC URL Form is `JDBC:TYPE://<HOST>:<PORT>/<DATABASE>`

if you connect with following this url ( `JDBC:TYPE://<HOST>:<PORT>/`  ) it means, connect to default database.

so, It doesn't work the way you want it to.

currently, Currently this doesn't support like you want. ( connect with default graph_path )
